modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="finkkk"
logoFile="sable_quota.png"
description='''
Sable Quota provides persistent per-player structure limits for Sable.
It protects creation and splitting paths, displays Action Bar feedback, and includes server administration commands.

Sable Quota 为 Sable 添加基于玩家的物理结构配额限制系统。
它覆盖结构创建与断裂路径，提供 Action Bar 提示、持久化个人上限和服务器管理指令。
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]

    modId="neoforge"
    type="required"
    versionRange="[21.1.233,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sable"
    type="required"
    versionRange="[2.0.3,)"
    ordering="AFTER"
    side="BOTH"
